#:schema node_modules/wrangler/config-schema.json
name = "hyperdrive-test"
main = "src/index.ts"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat_v2"]

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[vars]
ENVIRONMENT = "dev"

[[durable_objects.bindings]]
name = "POSTGRES_OBJECT"
class_name = "PostgresObject"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["PostgresObject"]

# Bind a Hyperdrive configuration. Use to accelerate access to your existing databases from Cloudflare Workers.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#hyperdrive
[[hyperdrive]]
binding = "HYPERDRIVE"
id = "HYPERDRIVE_ID"
localConnectionString = "postgresql://user:password@localhost:5432/database"

[env.staging]
hyperdrive = [{ binding = "HYPERDRIVE", id = "HYPERDRIVE_ID" }]
vars = { ENVIRONMENT = "staging" }
durable_objects.bindings = [{ name = "POSTGRES_OBJECT", class_name = "PostgresObject" }]
